### PR TITLE
tshev: remove some unnecessary copies of huge objects

### PR DESCRIPTION
**Pull request by tshev**

### CODE REVIEW

**Comment by tshev** [comment]
@EdouardGrave, @Celebio, @cpuhrsch, @piotr-bojanowski
I've made a few very obvious performance improvements. They don't make code more complicated and they can't sacrifice correctness code correctness. Could you review them, please?

**Comment by Celebio** [comment]
Hi @tshev ,
Thank you for the pull request. It looks very good, we will review it, but we can't tell when and if we will merge it (because it may interfere/conflict with our internal roadmap, independently from the quality of your commit)

Thank you again.
Regards,
Onur

**Comment by tshev** [comment]
@Celebio, thank for so quick reply.

**Comment by tshev** [comment]
@Celebio P. S.: I have a few more improvements in my local branch, but they are not as simple as these. Also, I have tweaked some compiler parameters and got 20% faster training.

**Comment by Celebio** [comment]
Hi @tshev ,
Why did you close the pull request?

Regards,
Onur

**Comment by tshev** [comment]
Hi @Celebio,

I thought it is unlikely to be merged. Also, I have a few more interesting improvements, which I would like to share with the community.

**Comment by tshev** [comment]
@Celebio Here I've added some extra improvements https://github.com/tshev/faster-FastText
For, example we can allow the compiler to generate SIMD-instructions for arithmetic operations with  floating-point numbers.

Kind regards,
Taras

**Pull request closed without merging**
