### PR TITLE
Add a shared object for the PHP binding.

### PR DESCRIPTION
**Pull request by YujiroTakahashi**
PHP bindings for fastText.

### CODE REVIEW

**Comment by cpuhrsch** [comment]
Hello @YujiroTakahashi,

Thank you for your pull request and for being an active member of our community. For now, we don't want to officially support php and hence can't merge these changes as we'd have to also provide maintenance. It is however possible to list these as part of our README, if they are in a separate github repository and refer to them as third-party php bindings.

With respect to the changes you suggested to be applied to the Makefile, can you instead use the recently added CMakeLists.txt file to generate the desired files?

Thank you,
Christian

**Comment by YujiroTakahashi** [comment]
Hello Christian,

Thank you for adding support for CMake.
My problems is all resolved.

[PHP bindings for fastText.](https://github.com/YujiroTakahashi/fastText-php)

Thank you,
Yujiro Takahashi.

**Comment by cpuhrsch** [comment]
Hello @YujiroTakahashi,

Does our CMake support also resolve your other pull request https://github.com/facebookresearch/fastText/pull/292?

Thank you,
Christian

**Comment by YujiroTakahashi** [comment]
Hello Christian,

I solved  #292 with cmake support.

Thank you,
Yujiro Takahashi.

**Comment by cpuhrsch** [comment]
Hello @YujiroTakahashi,

I'm closing this pull request now as it appears resolved. Thank you again for being an active member of our community.

Best,
Christian

**Pull request closed without merging**
