### PR TITLE
support different weight for each class in loss function

### PR DESCRIPTION
**Pull request by blackyang**
see #141 

add a `-weightBalanced ` argument to enable the weight to be inversely proportional to number of instances in that class. After that, normalize the class weights again such that sum(class weights) = nlabels.

Code should be very straightforward, it only takes me couple of minutes. However I am not an c++ expert, so please let me know if there is any problem for example running speed:)

### CODE REVIEW

**Comment by avanwouwe** [comment]
Hi,

You closed the request but the code does not seem to have been merged into master. Was it refused? If so, why? I'm very interested in the feature, and would love to use your code, unless it was refused due to issues? =)

**Comment by blackyang** [comment]
Hi @avanwouwe It was not refused, I closed it.

I just found that my implementation would slow down the code about 5x-10x (still okay since fastText is so fast:P). The reason is that `classWeights` is declared in every function call of `model.update()`. I should make it a shared variable.

**Comment by avanwouwe** [comment]
Yes I saw that =) And it seems to me strange that at each update you multiply the entire loss with each label weight, instead of penalising the loss calculated by the loss function, before adding it to the global loss. Or is that intentional?

Is there any reason why in line 275 of fastText.cc you are multiplying with sum_? It should be the sum of the probabilities, so always just 1.. right? Just wondering, but would it not be better to mutliply with the inverse of the class frequency normalised by the smallest frequency? I.e. 1 / (classFreq / minFreq). That way the penalisation factor is 1 if all classes are equal, and diminishes impact on the loss of more frequent classes.

**Comment by blackyang** [comment]
@avanwouwe oh right, good catch! Thanks

In line 275, I was trying to normalize it by total "votes". For example previously since each class has a weight of 1, then the total would be #classes. After assigning different weights to different classes, I still want the total to be #classes.

I think your solution is also good. BTW, in your case class weights are always < 1

**Comment by joneidejohnsen** [comment]
Any updates on this?

**Comment by simon19891101** [comment]
Hi all, just wonder if there are any updates? Cheers.

**Pull request closed without merging**
