### PR TITLE
fixed the python memory leak

### PR DESCRIPTION
**Pull request by lukeshuo**
related to the issue #841

### CODE REVIEW

**Comment by Celebio** [comment]
Hi @lukeshuo ,
Thank you for the pull request.
Did you test on both Python2 and Python3 ?

Best regards,
Onur

**Comment by lukeshuo** [comment]
> Hi @lukeshuo ,
> Thank you for the pull request.
> Did you test on both Python2 and Python3 ?
> 
> Best regards,
> Onur

Sorry, it was only tested on python3.

I just did a test on python2, found there is still a memory leak. After adding a few lines of code, the problem is fixed.

Now, the memory leak has been fixed on both python2 and python3. I will push a commit later.

Regards,

Luke

**Comment by Celebio** [comment]
Hi @lukeandshuo ,
I checked with valgrind and custom built (debug enabled) Python2 and Python3.
The commit fixes the issue.

Thank you for your contribution!

Best regards,
Onur

**Comment by zabatani** [comment]
I'm still experiencing a memory leak on Python3 when using fasttext 0.9.1, did this commit make it to release?

**Comment by davidefiocco** [comment]
Hi @zabatani , I don't think so. I have opened https://github.com/facebookresearch/fastText/issues/875 but that's still open.

**Pull request closed without merging**
