### PR TITLE
Add Swahili pre-trained vectors

### PR DESCRIPTION
**Pull request by poppingtonic**
I've created a new set of vectors, from a preprocessed version of the Swahili Wikipedia.

### CODE REVIEW

**Comment by poppingtonic** [comment]
How this was done:
+ Download the [Swahili WikiPedia dump](https://dumps.wikimedia.org/swwiki/20170301/swwiki-20170301-pages-articles-multistream.xml.bz2)
+ `bzip2 -d swwiki-20170301-pages-articles-multistream.xml.bz2`
+ `perl wikifil.pl swwiki-20170301-pages-articles-multistream.xml > wiki_dataset_cleaned.txt`
+ `fasttext skipgram -input wiki_dataset_cleaned.txt -output swahili_model`

**Comment by poppingtonic** [comment]
Update: Forgot license. I'm updating the archive, and will update the url.

**Comment by poppingtonic** [comment]
This is ready for review.

**Comment by cpuhrsch** [comment]
Hello @poppingtonic,

Thank you for your pull request and thank you for being an active member of our community. Unfortunately we cannot add a link whose content we do not own to our website. I'm noting down a task to build these embeddings and add them to the list once the time comes. Please note that we're currently working on [various](https://github.com/facebookresearch/fastText/issues/356) [aspects](https://github.com/facebookresearch/fastText/issues/355) [issues](https://github.com/facebookresearch/fastText/issues/327) related to some of our [embeddings]. It is therefore most likely that we will add embeddings for this language in context of a larger update. I'm closing this pull request now, but please feel free to reopen it if you don't consider it resolved.

Thank you,
Christian

**Pull request closed without merging**
