### PR TITLE
Fixes spelling in README

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by Santhosh-KS** [comment]
I've done some code changes. Would like to push it to the main repo. I'm not able to do so with some permission issues. Can any one help me getting my changes in to the repo?

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3913684).

**Pull request closed without merging**
