### PR TITLE
added threshold arg to test function

### PR DESCRIPTION
**Pull request by raghavjajodia**
Need threshold arg in test function, in python binding

### CODE REVIEW

**Comment by raghavjajodia** [comment]
Hi @Celebio  
Can you please look at this small feature request/bug fix?

**Comment by raghavjajodia** [comment]
Hi @Celebio , I see some warning during the build.. Can you tell what are the issues with this pull request? Thanks

**Comment by Celebio** [comment]
Hi @raghavjajodia ,
They are probably not related to your diff. Which warnings exactly do you get? 

Regards,
Onur

**Comment by raghavjajodia** [comment]
So, was this build successful ?  If yes, do you know how will this get merged to the master branch?
I am not able to see the exact warnings. This is what I see - 
linter
fbInternal

**Comment by lukasstreit** [comment]
This option is very important to a project I'm currently working on, thanks @raghavjajodia for this pull request.

@Celebio it would be awesome if you could give us an update about whether there's anything keeping this from being merged. If there's something I can help out with, please let me know.

**Pull request closed without merging**
