### PR TITLE
Add support for predicting k best labels

### PR DESCRIPTION
**Pull request by tomtung**

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by alexbeletsky** [comment]
That looks very interesting and actually something that I need for the problem I solving. We are classifying documents, that might belong to N classes and k best labels, seems something very valuable. Unfortunately I can't validate the correctness of this implementation, hopefully authors will review and merge that soon.

**Comment by tomtung** [comment]
FYI I have also pushed changes to a separate branch based on this one, adding support for outputting label probabilities: https://github.com/tomtung/fastText/commit/33a012c423c59568f3f0a54a33115620f9401b32

Will open another pull request after this one is merged.

**Comment by EdouardGrave** [comment]
Thanks, I will look at this later this week.

**Comment by xiamx** [comment]
@tomtung awesome work, it solves the problem for me :) Had I not seen this I'd waste some time duplicating the effort.

**Comment by tomtung** [comment]
Lol in retrospect, it was probably typical over-optimization for me to use unrestricted union, just to avoid heap allocation in the single label case. Without that the code is indeed cleaner. Good call removing that :)

**Pull request merged**
