### PR TITLE
Fixed compilation problems on Windows

### PR DESCRIPTION
**Pull request by rafael-aero**
Missing flag on opening and closing streams as binary for saving and
loading the model file (the other streams are fine, as they should open
in text mode to have auto-normalization of line endings)

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by Vaisman** [comment]
May be better use CMake? To be compatible with any version of Visual Studio and CLion.

**Comment by rafael-aero** [comment]
Probably a good idea - I'll take a look on it! Meanwhile, could you commit the change to the fasttext.cc file, just to add the right flags to the stream?

**Comment by cpuhrsch** [comment]
Hello @rafael-aero ,

Thank you for your pull request and for being an active member of our community! We recently added support for cmake. This should also work for Windows, but please let me know if this is not the case for you. We also resolved the compilation issue you're mentioning here. I'm going to close this pull request for now, but please feel free to reopen it at any time if your issue isn't resolved.

Thanks,
Christian

**Pull request closed without merging**
