### PR TITLE
match args.cc current minCount & verbose values in README

### PR DESCRIPTION
**Pull request by gojomo**
README command help text updated to match current args.cc defaults.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by piotr-bojanowski** [comment]
Thanks for the tip! The issue is that the default value for minCount depends on the "mode" that you use. It is set to 1 for `fasttext supervised` and to 5 for the rest...

**Comment by gojomo** [comment]
Aha! I find such subtly-varying defaults a bit confusing – and hard to document – but have updated the proposed changes to be clear that defaults for `supervised` mode are being shown, and other modes' defaults differ.

**Pull request merged**
